#!/bin/bash

__directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${__directory}/bashrc

local-build() {
  local __version="1.8.3"
  if [ ! -z "${1}" ]; then
    __version="${1}"
  fi
  local __package="packer_${__version}_linux_amd64.zip"

  mkdir -p ${__directory}/build
  mkdir -p ${__directory}/bin

  mkdir -p ${PACKER_CONFIG_DIR}
  mkdir -p ${PACKER_CACHE_DIR}
  mkdir -p ${PACKER_PLUGIN_PATH}
  touch ${PACKER_LOG_PATH}

  mkdir -p ${PACKER_INFRASTRUCTURE_ANSIBLE_ROLES_PATH}
  mkdir -p ${PACKER_INFRASTRUCTURE_ANSIBLE_COLLECTIONS_PATH}

  echo "Local install of Ansible roles and collections..."
  ansible-galaxy role install --roles-path ${PACKER_INFRASTRUCTURE_ANSIBLE_ROLES_PATH} -r ${__directory}/requirements.ansible.yml
  ansible-galaxy collection install --collections-path ${PACKER_INFRASTRUCTURE_ANSIBLE_COLLECTIONS_PATH} -r ${__directory}/requirements.ansible.yml

  echo "Local install of Packer..."
  wget -O ${__directory}/build/${__package} https://releases.hashicorp.com/packer/${__version}/${__package}
  unzip ${__directory}/build/${__package} -d ${__directory}/bin

  echo "Local install of Packer plugins..."
  packer init ${__directory}/requirements.pkr.hcl

  env | grep PACKER | sort
}

local-clean() {
  rm -rf ${__directory}/build
  rm -rf ${__directory}/bin
}